### PR TITLE
docs: clean up injected README

### PR DESCRIPTION
**Pull request by mariuslundgard**
- Only show `npm` installation example
- Format usage example as TypeScript with prettier
- Link to license file

### CODE REVIEW

**Review by snorrees — APPROVED** [review]
Cool, I'll follow up later and fix the semver-workflow bit, its not really compatible with this.

We also really should template in author on the license, as we have that info when we generate this.

**Comment by mariuslundgard** [comment]
OK, I'll let you merge this when you've done that, then!

**Comment by snorrees** [comment]
Oh, and feel free to mint a new version after you merge: manually triggered from actions (we dont do auto release on main)

**Comment by snorrees** [comment]
> OK, I'll let you merge this when you've done that, then!

Its already not compatible, so feel free to merge now.

**Pull request merged**
